<?php

/*********************************************************************
 * Extension configuration file for ext "imagetooltips".
 *
 * Generated by ext 16-09-2013 17:30 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Image tooltips',
	'description' => 'jquery TOOLS tooltips for tt_content images',
	'category' => 'fe',
	'shy' => 0,
	'version' => '0.2.0',
	'dependencies' => 'cms',
	'conflicts' => '',
	'priority' => '',
	'loadOrder' => '',
	'module' => '',
	'state' => 'stable',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearcacheonload' => 1,
	'lockType' => '',
	'author' => 'Alexander Stehlik',
	'author_email' => 'alexander.stehlik.deleteme@gmail.com',
	'author_company' => '',
	'CGLcompliance' => '',
	'CGLcompliance_note' => '',
	'constraints' =>
	array(
		'depends' =>
		array(
			'php' => '5.3.0-0.0.0',
			'typo3' => '4.5.0-6.2.99',
			'css_styled_content' => '',
		),
		'conflicts' =>
		array(),
		'suggests' =>
		array(),
	),
	'_md5_values_when_last_written' => 'a:17:{s:12:"ext_icon.gif";s:4:"1456";s:17:"ext_localconf.php";s:4:"3314";s:14:"ext_tables.php";s:4:"66a0";s:14:"ext_tables.sql";s:4:"a932";s:12:"t3jquery.txt";s:4:"7061";s:25:"Classes/TooltipPlugin.php";s:4:"5de0";s:21:"Configuration/Tca.php";s:4:"a3a4";s:38:"Configuration/TypoScript/constants.txt";s:4:"7932";s:34:"Configuration/TypoScript/setup.txt";s:4:"607f";s:42:"Configuration/TypoScript/4.5/constants.txt";s:4:"7932";s:38:"Configuration/TypoScript/4.5/setup.txt";s:4:"e884";s:42:"Configuration/TypoScript/Example/setup.txt";s:4:"18e7";s:43:"Resources/Private/Language/locallang_db.xml";s:4:"3737";s:32:"Resources/Public/Css/Example.css";s:4:"5fd9";s:52:"Resources/Public/JavaScript/TooltipInitialization.js";s:4:"c4cd";s:14:"doc/manual.pdf";s:4:"e60d";s:14:"doc/manual.sxw";s:4:"6843";}',
	'suggests' =>
	array(),
);

?>